name: Close fixed issues

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  fixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4.1.0
      with:
        days-before-stale: 0
        days-before-close: 0
        ignore-updates: true
        remove-stale-when-updated: false
        close-issue-message: >-
          This issue has been fixed in the latest release of this extension,
          which is available in the VS Code extension marketplace.
        stale-issue-label: fixed-pending-release
        only-labels: fixed-pending-release
